function communityEditor() {
  return `<dialog id="community-editor" class="creator-dialog community-editor" aria-labelledby="community-editor-title"><form method="dialog"><button class="dialog-close" aria-label="Close community editor">×</button></form><span class="eyebrow accent" id="community-editor-label">[ SAME TOKEN. NEW HOME. ]</span><h2 id="community-editor-title">Bring your people.</h2><div id="community-editor-content"></div><p id="community-editor-message" class="community-form-message" role="status" aria-live="polite"></p></dialog>`;
}

export function communitiesPage() {
  return `<div id="communities-app" data-community-view="directory"><header class="communities-hero"><div class="communities-hero-copy"><span class="eyebrow accent">[ A HOME FOR YOUR PEOPLE ]</span><h1>Your token.<br>Your <span>corner.</span></h1><p>Already have a token on Solana? Bring its identity to Nikki. Give the community somewhere to talk, share, and stay.</p><div class="btn-row"><button class="btn btn-primary" data-community-import>Bring a community ↗</button><a class="btn" href="#community-directory">Find your people ↓</a></div><p class="communities-hero-note">Existing tokens welcome. Text posts cost nothing.</p></div><div class="communities-art" aria-hidden="true"><div class="communities-art-heading">THE GROUP CHAT<br>FOUND A HOME.</div><div class="communities-art-message communities-art-message-one"><span>↗</span> we're here.</div><div class="communities-art-message communities-art-message-two"><span>♡</span> all of us?</div><div class="communities-art-message communities-art-message-three">all of us. <span>✳</span></div><span class="communities-art-sticker">POST.<br>FOR FREE.</span></div></header><div class="communities-strip" aria-label="How communities work"><span><b>01</b> Import your token</span><span><b>02</b> Make it your space</span><span><b>03</b> Start talking</span></div><section id="community-directory" class="communities-directory" aria-labelledby="communities-directory-title"><div class="communities-section-heading"><div><span class="eyebrow accent">[ FIND YOUR CORNER ]</span><h2 id="communities-directory-title">Communities<span class="accent">.</span></h2></div><span class="community-count" id="communities-count" aria-live="polite">LOOKING AROUND…</span></div><div class="communities-search"><label for="communities-search">Find your people</label><div><span aria-hidden="true">⌕</span><input id="communities-search" type="search" maxlength="100" autocomplete="off" placeholder="Search a name, symbol, or token address…"></div></div><div id="communities-results" aria-live="polite" aria-busy="true"><div class="community-empty"><span class="community-empty-mark" aria-hidden="true">✳</span><h3>Finding the good company…</h3><p>Loading communities on Nikki.</p></div></div><button class="btn communities-more" id="communities-more" hidden>More communities ↓</button><aside class="communities-footnote"><strong>A space to belong. No buy-in required.</strong><p>Joining a community is free and separate from holding its token. Text posts live on Nikki and can be removed; permanent video storage is a separate, paid step.</p></aside></section>${communityEditor()}</div>`;
}

export function communityPage() {
  return `<div id="communities-app" data-community-view="detail"><a class="community-back" href="/communities/">← All communities</a><div id="community-detail" aria-live="polite" aria-busy="true"><div class="community-empty"><span class="community-empty-mark" aria-hidden="true">✳</span><h1>Opening this corner…</h1><p>Finding the community and its conversations.</p></div></div>${communityEditor()}</div>`;
}
